= Vert.x Consul Client

https://www.consul.io[Consul] is a tool for discovering and configuring services in your infrastructure.

A Vert.x client allowing applications to interact with a Consul system via blocking and non-blocking HTTP API.

== Using Vert.x Consul Client

To use this project, add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-consul-client</artifactId>
  <version>3.4.0-SNAPSHOT</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-consul-client:3.4.0-SNAPSHOT'
----

== Creating a client

Just use factory method:

[source,js]
----
var ConsulClient = require("vertx-consul-js/consul_client");

var client = ConsulClient.create(vertx);


----

Also the client can be configured with an options.

[source,js]
----
var ConsulClient = require("vertx-consul-js/consul_client");

var options = {
  "host" : "consul.example.com"
};

var client = ConsulClient.create(vertx, options);


----

The following configuration is supported by the consul client:

`host`:: Consul host. Defaults to `localhost`
`port`:: Consul HTTP API port. Defaults to `8500`
`timeout`:: Sets the amount of time (in milliseconds) after which if the request does not return any data
within the timeout period an failure will be passed to the handler and the request will be closed.
`acl_token`:: The ACL token. When provided, the client will use this token when making requests to the Consul
by providing the "?token" query parameter. When not provided, the empty token, which maps to the 'anonymous'
ACL policy, is used.
`dc`:: The datacenter name. When provided, the client will use it when making requests to the Consul
by providing the "?dc" query parameter. When not provided, the datacenter of the consul agent is queried.

== Using the API

The client API is represented by `link:../../jsdoc/module-vertx-consul-js_consul_client-ConsulClient.html[ConsulClient]`. The API is very similar to Consul's
HTTP API that described in https://www.consul.io/docs/agent/http.html[Consul API docs]

=== Blocking queries

Certain endpoints support a feature called a "blocking query." A blocking query is used to wait for a potential
change using long polling. Any endpoint that supports blocking also provide a unique identifier (index) representing
the current state of the requested resource. The following configuration is used to perform blocking queries:

`index`:: value indicating that the client wishes to wait for any changes subsequent to that index.
`wait`:: parameter specifying a maximum duration for the blocking request. This is limited to 10 minutes.

[source,js]
----

var opts = {
  "index" : lastIndex,
  "wait" : "1m"
};


----

== Key/Value Store

The KV endpoints are used to access Consul's simple key/value store, useful for storing service configuration or other metadata.
The following endpoints are supported:

* To manage updates of individual keys, deletes of individual keys or key prefixes, and fetches of individual keys or key prefixes
* To manage updates or fetches of multiple keys inside a single, atomic transaction

=== Get key-value pair from store

Consul client can return the value for certain key

[source,js]
----

consulClient.getValue("key", function (res, res_err) {
  if (res_err == null) {
    console.log("retrieved value: " + res.value);
    console.log("modify index: " + res.modifyIndex);
  } else {
    res_err.printStackTrace();
  }
});


----

...or it can return all key-value pairs with the given prefix

[source,js]
----

consulClient.getValues("prefix", function (res, res_err) {
  if (res_err == null) {
    console.log("modify index: " + res.index);
    Array.prototype.forEach.call(res.list, function(kv) {
      console.log("retrieved value: " + kv.value);
    });
  } else {
    res_err.printStackTrace();
  }
});


----

The returned key-value object contains these fields (see https://www.consul.io/docs/agent/http/kv.html#single[documentation]):

`createIndex`:: the internal index value that represents when the entry was created.
`modifyIndex`:: the last index that modified this key
`lockIndex`:: the number of times this key has successfully been acquired in a lock
`key`:: the key
`flags`:: the flags attached to this entry. Clients can choose to use this however makes
sense for their application
`value`:: the value
`session`:: the session that owns the lock

The modify index can be used for blocking queries:

[source,js]
----

var opts = {
  "index" : modifyIndex,
  "wait" : "1m"
};

consulClient.getValueWithOptions("key", opts, function (res, res_err) {
  if (res_err == null) {
    console.log("retrieved value: " + res.value);
    console.log("new modify index: " + res.modifyIndex);
  } else {
    res_err.printStackTrace();
  }
});


----

=== Put key-value pair to store

[source,js]
----

consulClient.putValue("key", "value", function (res, res_err) {
  if (res_err == null) {
    var opResult = res ? "success" : "fail";
    console.log("result of the operation: " + opResult);
  } else {
    res_err.printStackTrace();
  }
});


----

Put request with options also accepted

[source,js]
----

var opts = {
  "flags" : 42,
  "casIndex" : modifyIndex,
  "acquireSession" : "acquireSessionID",
  "releaseSession" : "releaseSessionID"
};

consulClient.putValueWithOptions("key", "value", opts, function (res, res_err) {
  if (res_err == null) {
    var opResult = res ? "success" : "fail";
    console.log("result of the operation: " + opResult);
  } else {
    res_err.printStackTrace();
  }
});


----

The list of the query options that can be used with a `PUT` request:

`flags`:: This can be used to specify an unsigned value between `0` and `2^64^-1`.
Clients can choose to use this however makes sense for their application.
`casIndex`:: This flag is used to turn the PUT into a Check-And-Set operation. This is very useful as a building
block for more complex synchronization primitives. If the index is `0`, Consul will only put the key if it does
not already exist. If the index is non-zero, the key is only set if the index matches the ModifyIndex of that key.
`acquireSession`:: This flag is used to turn the PUT into a lock acquisition operation. This is useful
as it allows leader election to be built on top of Consul. If the lock is not held and the session is valid,
this increments the LockIndex and sets the Session value of the key in addition to updating the key contents.
A key does not need to exist to be acquired. If the lock is already held by the given session, then the LockIndex
is not incremented but the key contents are updated. This lets the current lock holder update the key contents
without having to give up the lock and reacquire it.
`releaseSession`:: This flag is used to turn the PUT into a lock release operation. This is useful when paired
with `acquireSession` as it allows clients to yield a lock. This will leave the LockIndex unmodified but will clear
the associated Session of the key. The key must be held by this session to be unlocked.

=== Transactions

When connected to Consul 0.7 and later, client allows to manage updates or fetches of multiple keys
inside a single, atomic transaction. KV is the only available operation type, though other types of operations
may be added in future versions of Consul to be mixed with key/value operations
(see https://www.consul.io/docs/agent/http/kv.html#txn[documentation]).

[source,js]
----

var request = {
  "operations" : [
    {
      "key" : "key1",
      "value" : "value1",
      "type" : "SET"
    },
    {
      "key" : "key2",
      "value" : "value2",
      "type" : "SET"
    }
  ]
};

consulClient.transaction(request, function (res, res_err) {
  if (res_err == null) {
    console.log("succeeded results: " + res.results.length);
    console.log("errors: " + res.errors.length);
  } else {
    res_err.printStackTrace();
  }
});

----

=== Delete key-value pair

At last, Consul client allows to delete key-value pair from store:

[source,js]
----

consulClient.deleteValue("key", function (res, res_err) {
  if (res_err == null) {
    console.log("complete");
  } else {
    res_err.printStackTrace();
  }
});


----

...or all key-value pairs with corresponding key prefix

[source,js]
----

consulClient.deleteValues("prefix", function (res, res_err) {
  if (res_err == null) {
    console.log("complete");
  } else {
    res_err.printStackTrace();
  }
});


----

== Health Checks

TBD
[source,js]
----

var alwaysGood = function (h) {
  h.response().setStatusCode(200).end();
};

// create HTTP server to responce health check

vertx.createHttpServer().requestHandler(alwaysGood).listen(4848);

// check health via TCP port every 1 sec

var opts = {
  "tcp" : "localhost:4848",
  "interval" : "1s"
};

// register TCP check

consulClient.registerCheck(opts, function (res, res_err) {

  if (res_err == null) {

    console.log("check successfully registered");

  } else {

    res_err.printStackTrace();

  }

});

----

== Services

TBD
[source,js]
----

var opts = {
  "id" : "serviceId",
  "name" : "serviceName",
  "tags" : ["tag1", "tag2"],
  "checkOptions" : {
    "ttl" : "10s"
  },
  "address" : "10.0.0.1",
  "port" : 8080
};

// Service registration

consulClient.registerService(opts, function (res, res_err) {

  if (res_err == null) {

    console.log("Service successfully registered");

  } else {

    res_err.printStackTrace();

  }

});

// Discovery registered service

consulClient.catalogServiceNodes("serviceName", function (res, res_err) {

  if (res_err == null) {

    console.log("found " + res.list.length + " services");

    console.log("consul state index: " + res.index);

    Array.prototype.forEach.call(res.list, function(service) {

      console.log("Service node: " + service.node);

      console.log("Service address: " + service.address);

      console.log("Service port: " + service.port);

    });

  } else {

    res_err.printStackTrace();

  }

});

// Blocking request for nodes that provide given service, sorted by distance from agent

var queryOpts = {
  "near" : "_agent",
  "blockingOptions" : {
    "index" : lastIndex
  }
};

consulClient.catalogServiceNodesWithOptions("serviceName", queryOpts, function (res, res_err) {

  if (res_err == null) {

    console.log("found " + res.list.length + " services");

  } else {

    res_err.printStackTrace();

  }

});

// Service deregistration

consulClient.deregisterService("serviceId", function (res, res_err) {

  if (res_err == null) {

    console.log("Service successfully deregistered");

  } else {

    res_err.printStackTrace();

  }

});


----

== Events

TBD
[source,js]
----

var opts = {
  "tag" : "tag",
  "payload" : "message"
};

// trigger a new user event

consulClient.fireEventWithOptions("eventName", opts, function (res, res_err) {

  if (res_err == null) {

    console.log("Event sent");

    console.log("id: " + res.id);

  } else {

    res_err.printStackTrace();

  }

});

// most recent events known by the agent

consulClient.listEvents(function (res, res_err) {

  if (res_err == null) {

    Array.prototype.forEach.call(res.list, function(event) {

      console.log("Event id: " + event.id);

      console.log("Event name: " + event.name);

      console.log("Event payload: " + event.payload);

    });

  } else {

    res_err.printStackTrace();

  }

});


----

== Sessions

TBD
[source,js]
----

var opts = {
  "node" : "nodeId",
  "behavior" : "RELEASE"
};

// Create session

consulClient.createSessionWithOptions(opts, function (res, res_err) {

  if (res_err == null) {

    console.log("Session successfully created");

    console.log("id: " + res);

  } else {

    res_err.printStackTrace();

  }

});

// Lists sessions belonging to a node

consulClient.listNodeSessions("nodeId", function (res, res_err) {

  if (res_err == null) {

    Array.prototype.forEach.call(res.list, function(session) {

      console.log("Session id: " + session.id);

      console.log("Session node: " + session.node);

      console.log("Session create index: " + session.createIndex);

    });

  } else {

    res_err.printStackTrace();

  }

});

// Blocking query for all active sessions

var blockingOpts = {
  "index" : lastIndex
};

consulClient.listSessionsWithOptions(blockingOpts, function (res, res_err) {

  if (res_err == null) {

    console.log("Found " + res.list.length + " sessions");

  } else {

    res_err.printStackTrace();

  }

});

// Destroy session

consulClient.destroySession(sessionId, function (res, res_err) {

  if (res_err == null) {

    console.log("Session successfully destroyed");

  } else {

    res_err.printStackTrace();

  }

});


----

== Nodes in cluster

TBD
[source,js]
----

consulClient.catalogNodes(function (res, res_err) {

  if (res_err == null) {

    console.log("found " + res.list.length + " nodes");

    console.log("consul state index " + res.index);

  } else {

    res_err.printStackTrace();

  }

});

// blocking request to catalog for nodes, sorted by distance from agent

var opts = {
  "near" : "_agent",
  "blockingOptions" : {
    "index" : lastIndex
  }
};

consulClient.catalogNodesWithOptions(opts, function (res, res_err) {

  if (res_err == null) {

    console.log("found " + res.list.length + " nodes");

  } else {

    res_err.printStackTrace();

  }

});


----