= Vert.x Consul Client

https://www.consul.io[Consul] is a tool for discovering and configuring services in your infrastructure.

A Vert.x client allowing applications to interact with a Consul system via blocking and non-blocking HTTP API.

== Using Vert.x Consul Client

To use this project, add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-consul-client</artifactId>
  <version>3.4.0-SNAPSHOT</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-consul-client:3.4.0-SNAPSHOT'
----

== Creating a client

Just use factory method:

[source,ruby]
----
require 'vertx-consul/consul_client'

client = VertxConsul::ConsulClient.create(vertx)


----

Also the client can be configured with a json object.

[source,ruby]
----
require 'vertx-consul/consul_client'

config = {
  'host' => "consul.example.com"
}

client = VertxConsul::ConsulClient.create(vertx, config)


----

The following configuration is supported by the consul client:

`host`:: Consul host. Defaults to `localhost`
`port`:: Consul HTTP API port. Defaults to `8500`
`timeout`:: Sets the amount of time (in milliseconds) after which if the request does not return any data
within the timeout period an failure will be passed to the handler and the request will be closed.
`acl_token`:: The ACL token. When provided, the client will use this token when making requests to the Consul
by providing the "?token" query parameter. When not provided, the empty token, which maps to the 'anonymous'
ACL policy, is used.
`dc`:: The datacenter name. When provided, the client will use it when making requests to the Consul
by providing the "?dc" query parameter. When not provided, the datacenter of the consul agent is queried.

== Using the API

The client API is represented by `link:../../yardoc/VertxConsul/ConsulClient.html[ConsulClient]`.

=== Key/Value Store

[source,ruby]
----

# put Key/Value pair to Consul Store
consulClient.put_value("foo", "bar") { |res_err,res|

  if (res_err == nil)

    puts "result of the operation: #{(res ? "success" : "fail")}"

  else

    res_err.print_stack_trace()

  end

}

#  get Key/Value pair from Consul Store
consulClient.get_value("foo") { |res_err,res|

  if (res_err == nil)

    puts "retrieved value: #{res['value']}"

  else

    res_err.print_stack_trace()

  end

}


----

=== Health Checks

[source,ruby]
----

alwaysGood = lambda { |h|
  h.response().set_status_code(200).end()
}

# create HTTP server to responce health check

vertx.create_http_server().request_handler(&alwaysGood).listen(4848)

# check health via TCP port every 1 sec

opts = {
  'tcp' => "localhost:4848",
  'interval' => "1s"
}

# register TCP check

consulClient.register_check(opts) { |res_err,res|

  if (res_err == nil)

    puts "check successfully registered"

  else

    res_err.print_stack_trace()

  end

}

----

=== Service discovery

[source,ruby]
----

consulClient.catalog_service_nodes("consul") { |res_err,res|

  if (res_err == nil)

    serviceList = res

    puts "found #{serviceList.length} services"

    serviceList.each do |service|

      puts "Service node: #{service['node']}"

      puts "Service node address: #{service['nodeAddress']}"

    end

  else

    res_err.print_stack_trace()

  end

}


----