= Vert.x Consul Client

https://www.consul.io[Consul] is a tool for discovering and configuring services in your infrastructure.

A Vert.x client allowing applications to interact with a Consul system via blocking and non-blocking HTTP API.

== Using Vert.x Consul Client

To use this project, add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-consul-client</artifactId>
  <version>3.4.0-SNAPSHOT</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-consul-client:3.4.0-SNAPSHOT'
----

== Creating a client

Just use factory method:

[source,kotlin]
----

var client = ConsulClient.create(vertx)


----

Also the client can be configured with an options.

[source,kotlin]
----

var options = ConsulClientOptions(
  host = "consul.example.com")

var client = ConsulClient.create(vertx, options)


----

The following configuration is supported by the consul client:

`host`:: Consul host. Defaults to `localhost`
`port`:: Consul HTTP API port. Defaults to `8500`
`timeout`:: Sets the amount of time (in milliseconds) after which if the request does not return any data
within the timeout period an failure will be passed to the handler and the request will be closed.
`acl_token`:: The ACL token. When provided, the client will use this token when making requests to the Consul
by providing the "?token" query parameter. When not provided, the empty token, which maps to the 'anonymous'
ACL policy, is used.
`dc`:: The datacenter name. When provided, the client will use it when making requests to the Consul
by providing the "?dc" query parameter. When not provided, the datacenter of the consul agent is queried.

ConsulClient options extends WebClientOptions from `vertx-web-client` module,
therefore a lot of settings are available. Please see the documentation.

== Using the API

The client API is represented by `link:../../apidocs/io/vertx/ext/consul/ConsulClient.html[ConsulClient]`. The API is very similar to Consul's
HTTP API that described in https://www.consul.io/docs/agent/http.html[Consul API docs]

=== Blocking queries

Certain endpoints support a feature called a "blocking query." A blocking query is used to wait for a potential
change using long polling. Any endpoint that supports blocking also provide a unique identifier (index) representing
the current state of the requested resource. The following configuration is used to perform blocking queries:

`index`:: value indicating that the client wishes to wait for any changes subsequent to that index.
`wait`:: parameter specifying a maximum duration for the blocking request. This is limited to 10 minutes.

[source,kotlin]
----

var opts = BlockingQueryOptions(
  index = lastIndex,
  wait = "1m")


----

A critical note is that the return of a blocking request is *no guarantee* of a change.
It is possible that the timeout was reached or that there was an idempotent write that does not affect the result of the query.

== Key/Value Store

The KV endpoints are used to access Consul's simple key/value store, useful for storing service configuration or other metadata.
The following endpoints are supported:

* To manage updates of individual keys, deletes of individual keys or key prefixes, and fetches of individual keys or key prefixes
* To manage updates or fetches of multiple keys inside a single, atomic transaction

=== Get key-value pair from store

Consul client can return the value for certain key

[source,kotlin]
----

consulClient.getValue("key", { res ->
  if (res.succeeded()) {
    println("retrieved value: ${res.result().value}")
    println("modify index: ${res.result().modifyIndex}")
  } else {
    res.cause().printStackTrace()
  }
})


----

...or it can return all key-value pairs with the given prefix

[source,kotlin]
----

consulClient.getValues("prefix", { res ->
  if (res.succeeded()) {
    println("modify index: ${res.result().index}")
    for (kv in res.result().list) {
      println("retrieved value: ${kv.value}")
    }
  } else {
    res.cause().printStackTrace()
  }
})


----

The returned key-value object contains these fields (see https://www.consul.io/docs/agent/http/kv.html#single[documentation]):

`createIndex`:: the internal index value that represents when the entry was created.
`modifyIndex`:: the last index that modified this key
`lockIndex`:: the number of times this key has successfully been acquired in a lock
`key`:: the key
`flags`:: the flags attached to this entry. Clients can choose to use this however makes
sense for their application
`value`:: the value
`session`:: the session that owns the lock

The modify index can be used for blocking queries:

[source,kotlin]
----

var opts = BlockingQueryOptions(
  index = modifyIndex,
  wait = "1m")

consulClient.getValueWithOptions("key", opts, { res ->
  if (res.succeeded()) {
    println("retrieved value: ${res.result().value}")
    println("new modify index: ${res.result().modifyIndex}")
  } else {
    res.cause().printStackTrace()
  }
})


----

=== Put key-value pair to store

[source,kotlin]
----

consulClient.putValue("key", "value", { res ->
  if (res.succeeded()) {
    var opResult = res.result() ? "success" : "fail"
    println("result of the operation: ${opResult}")
  } else {
    res.cause().printStackTrace()
  }
})


----

Put request with options also accepted

[source,kotlin]
----

var opts = KeyValueOptions(
  flags = 42,
  casIndex = modifyIndex,
  acquireSession = "acquireSessionID",
  releaseSession = "releaseSessionID")

consulClient.putValueWithOptions("key", "value", opts, { res ->
  if (res.succeeded()) {
    var opResult = res.result() ? "success" : "fail"
    println("result of the operation: ${opResult}")
  } else {
    res.cause().printStackTrace()
  }
})


----

The list of the query options that can be used with a `PUT` request:

`flags`:: This can be used to specify an unsigned value between `0` and `2^64^-1`.
Clients can choose to use this however makes sense for their application.
`casIndex`:: This flag is used to turn the PUT into a Check-And-Set operation. This is very useful as a building
block for more complex synchronization primitives. If the index is `0`, Consul will only put the key if it does
not already exist. If the index is non-zero, the key is only set if the index matches the ModifyIndex of that key.
`acquireSession`:: This flag is used to turn the PUT into a lock acquisition operation. This is useful
as it allows leader election to be built on top of Consul. If the lock is not held and the session is valid,
this increments the LockIndex and sets the Session value of the key in addition to updating the key contents.
A key does not need to exist to be acquired. If the lock is already held by the given session, then the LockIndex
is not incremented but the key contents are updated. This lets the current lock holder update the key contents
without having to give up the lock and reacquire it.
`releaseSession`:: This flag is used to turn the PUT into a lock release operation. This is useful when paired
with `acquireSession` as it allows clients to yield a lock. This will leave the LockIndex unmodified but will clear
the associated Session of the key. The key must be held by this session to be unlocked.

=== Transactions

When connected to Consul 0.7 and later, client allows to manage updates or fetches of multiple keys
inside a single, atomic transaction. KV is the only available operation type, though other types of operations
may be added in future versions of Consul to be mixed with key/value operations
(see https://www.consul.io/docs/agent/http/kv.html#txn[documentation]).

[source,kotlin]
----

var request = TxnRequest(
  operations = listOf(TxnKVOperation(
    key = "key1",
    value = "value1",
    type = TxnKVVerb.SET), TxnKVOperation(
    key = "key2",
    value = "value2",
    type = TxnKVVerb.SET)))

consulClient.transaction(request, { res ->
  if (res.succeeded()) {
    println("succeeded results: ${res.result().results.size}")
    println("errors: ${res.result().errors.size}")
  } else {
    res.cause().printStackTrace()
  }
})

----

=== Delete key-value pair

At last, Consul client allows to delete key-value pair from store:

[source,kotlin]
----

consulClient.deleteValue("key", { res ->
  if (res.succeeded()) {
    println("complete")
  } else {
    res.cause().printStackTrace()
  }
})


----

...or all key-value pairs with corresponding key prefix

[source,kotlin]
----

consulClient.deleteValues("prefix", { res ->
  if (res.succeeded()) {
    println("complete")
  } else {
    res.cause().printStackTrace()
  }
})


----

== Services

One of the main goals of service discovery is to provide a catalog of available services.
To that end, the agent provides a simple service definition format to declare the availability of a service
and to potentially associate it with a health check.

=== Service registering

A service definition must include a `name` and may optionally provide an `id`, `tags`, `address`, `port`, and `checks`.

[source,kotlin]
----

var opts = ServiceOptions(
  name = "serviceName",
  id = "serviceId",
  tags = listOf("tag1", "tag2"),
  checkOptions = CheckOptions(
    ttl = "10s"),
  address = "10.0.0.1",
  port = 8048)


----

`name`:: the name of service
`id`:: the `id` is set to the `name` if not provided. It is required that all services have a unique ID per node,
so if names might conflict then unique IDs should be provided.
`tags`:: list of values that are opaque to Consul but can be used to distinguish between primary or secondary nodes,
different versions, or any other service level labels.
`address`:: used to specify a service-specific IP address. By default, the IP address of the agent is used,
and this does not need to be provided.
`port`:: used as well to make a service-oriented architecture simpler to configure; this way,
the address and port of a service can be discovered.
`checks`:: associated health checks

These options used to register service in catalog:

[source,kotlin]
----

consulClient.registerService(opts, { res ->
  if (res.succeeded()) {
    println("Service successfully registered")
  } else {
    res.cause().printStackTrace()
  }

})


----

=== Service discovery

Consul client allows to obtain actual list of the nodes providing a service

[source,kotlin]
----

consulClient.catalogServiceNodes("serviceName", { res ->
  if (res.succeeded()) {
    println("found ${res.result().list.size} services")
    println("consul state index: ${res.result().index}")
    for (service in res.result().list) {
      println("Service node: ${service.node}")
      println("Service address: ${service.address}")
      println("Service port: ${service.port}")
    }
  } else {
    res.cause().printStackTrace()
  }
})


----

It is possible to obtain this list with the statuses of the associated health checks.
The result can be filtered by check status.

[source,kotlin]
----

consulClient.healthServiceNodes("serviceName", passingOnly, { res ->
  if (res.succeeded()) {
    println("found ${res.result().list.size} services")
    println("consul state index: ${res.result().index}")
    for (entry in res.result().list) {
      println("Service node: ${entry.node}")
      println("Service address: ${entry.service.address}")
      println("Service port: ${entry.service.port}")
    }
  } else {
    res.cause().printStackTrace()
  }
})


----

There are additional parameters for services queries

[source,kotlin]
----

var queryOpts = ServiceQueryOptions(
  tag = "tag1",
  near = "_agent",
  blockingOptions = BlockingQueryOptions(
    index = lastIndex))


----

`tag`:: by default, all nodes matching the service are returned.
The list can be filtered by tag using the `tag` query parameter
`near`:: adding the optional `near` parameter with a node name will sort the node list in ascending order
based on the estimated round trip time from that node. Passing `near`=`_agent` will use the agent's node for the sort.
`blockingOptions`:: the blocking qyery options

Then the request should look like

[source,kotlin]
----

consulClient.healthServiceNodesWithOptions("serviceName", passingOnly, queryOpts, { res ->
  if (res.succeeded()) {
    println("found ${res.result().list.size} services")
  } else {
    res.cause().printStackTrace()
  }

})

----

=== Deregister service

Service can be deregistered by its ID:

[source,kotlin]
----

consulClient.deregisterService("serviceId", { res ->
  if (res.succeeded()) {
    println("Service successfully deregistered")
  } else {
    res.cause().printStackTrace()
  }
})


----

== Health Checks

One of the primary roles of the agent is management of system-level and application-level health checks.
A health check is considered to be application-level if it is associated with a service.
If not associated with a service, the check monitors the health of the entire node.

[source,kotlin]
----

var opts = CheckOptions(
  tcp = "localhost:4848",
  interval = "1s")


----

The list of check options that supported by Consul client is:

`id`:: the check ID
`name`:: check name
`script`:: local path to checking script. Also you should set checking interval
`http`:: HTTP address to check. Also you should set checking interval
`ttl`:: Time to Live of check
`tcp`:: TCP address to check. Also you should set checking interval
`interval`:: checking interval in Go's time format which is sequence of decimal numbers,
each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m".
Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h"
`notes`:: the check notes
`serviceId`:: the service ID to associate the registered check with an existing service provided by the agent.
`deregisterAfter`:: deregister timeout. This is optional field, which is a timeout in the same time format as Interval and TTL.
If a check is associated with a service and has the critical state for more than this configured value,
then its associated service (and all of its associated checks) will automatically be deregistered.
The minimum timeout is 1 minute, and the process that reaps critical services runs every 30 seconds,
so it may take slightly longer than the configured timeout to trigger the deregistration.
This should generally be configured with a timeout that's much, much longer than any expected recoverable outage
for the given service.
`status`:: the check status to specify the initial state of the health check

The `Name` field is mandatory, as is one of `Script`, `HTTP`, `TCP` or `TTL`. `Script`, `TCP` and `HTTP`
also require that `Interval` be set. If an `ID` is not provided, it is set to `Name`.
You cannot have duplicate ID entries per agent, so it may be necessary to provide an ID.

[source,kotlin]
----

consulClient.registerCheck(opts, { res ->
  if (res.succeeded()) {
    println("check successfully registered")
  } else {
    res.cause().printStackTrace()
  }
})


----

== Events

The Consul provides a mechanism to fire a custom user event to an entire datacenter.
These events are opaque to Consul, but they can be used to build scripting infrastructure to do automated deploys,
restart services, or perform any other orchestration action.

To send user event only its name is required

[source,kotlin]
----

consulClient.fireEvent("eventName", { res ->
  if (res.succeeded()) {
    println("Event sent")
    println("id: ${res.result().id}")
  } else {
    res.cause().printStackTrace()
  }
})


----

Also additional options can be specified.

`node`:: regular expression to filter recipients by node name
`service`:: regular expression to filter recipients by service
`tag`:: regular expression to filter recipients by tag
`payload`:: an optional body of the event.
The body contents are opaque to Consul and become the "payload" of the event

[source,kotlin]
----

var opts = EventOptions(
  tag = "tag",
  payload = "message")

consulClient.fireEventWithOptions("eventName", opts, { res ->
  if (res.succeeded()) {
    println("Event sent")
    println("id: ${res.result().id}")
  } else {
    res.cause().printStackTrace()
  }
})


----

The Consul Client supports queries for obtain the most recent events known by the agent. Events are broadcast using
the gossip protocol, so they have no global ordering nor do they make a promise of delivery. Agents only buffer
the most recent entries. The current buffer size is 256, but this value could change in the future.

[source,kotlin]
----

consulClient.listEvents({ res ->
  if (res.succeeded()) {
    println("Consul index: ${res.result().index}")
    for (event in res.result().list) {
      println("Event id: ${event.id}")
      println("Event name: ${event.name}")
      println("Event payload: ${event.payload}")
    }
  } else {
    res.cause().printStackTrace()
  }
})


----

The Consul Index can be used to prepare blocking requests:

[source,kotlin]
----

var opts = EventListOptions(
  name = "eventName",
  blockingOptions = BlockingQueryOptions(
    index = lastIndex))

consulClient.listEventsWithOptions(opts, { res ->
  if (res.succeeded()) {
    println("Consul index: ${res.result().index}")
    for (event in res.result().list) {
      println("Event id: ${event.id}")
    }
  } else {
    res.cause().printStackTrace()
  }
})


----

== Sessions

TBD
[source,kotlin]
----

var opts = SessionOptions(
  node = "nodeId",
  behavior = SessionBehavior.RELEASE)

// Create session

consulClient.createSessionWithOptions(opts, { res ->

  if (res.succeeded()) {

    println("Session successfully created")

    println("id: ${res.result()}")

  } else {

    res.cause().printStackTrace()

  }

})

// Lists sessions belonging to a node

consulClient.listNodeSessions("nodeId", { res ->

  if (res.succeeded()) {

    for (session in res.result().list) {

      println("Session id: ${session.id}")

      println("Session node: ${session.node}")

      println("Session create index: ${session.createIndex}")

    }

  } else {

    res.cause().printStackTrace()

  }

})

// Blocking query for all active sessions

var blockingOpts = BlockingQueryOptions(
  index = lastIndex)

consulClient.listSessionsWithOptions(blockingOpts, { res ->

  if (res.succeeded()) {

    println("Found ${res.result().list.size} sessions")

  } else {

    res.cause().printStackTrace()

  }

})

// Destroy session

consulClient.destroySession(sessionId, { res ->

  if (res.succeeded()) {

    println("Session successfully destroyed")

  } else {

    res.cause().printStackTrace()

  }

})


----

== Nodes in cluster

TBD
[source,kotlin]
----

consulClient.catalogNodes({ res ->

  if (res.succeeded()) {

    println("found ${res.result().list.size} nodes")

    println("consul state index ${res.result().index}")

  } else {

    res.cause().printStackTrace()

  }

})

// blocking request to catalog for nodes, sorted by distance from agent

var opts = NodeQueryOptions(
  near = "_agent",
  blockingOptions = BlockingQueryOptions(
    index = lastIndex))

consulClient.catalogNodesWithOptions(opts, { res ->

  if (res.succeeded()) {

    println("found ${res.result().list.size} nodes")

  } else {

    res.cause().printStackTrace()

  }

})


----