= Cheatsheets

[[AclToken]]
== AclToken

++++
 Holds properties of Acl token
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[id]]`id`|`String`|
+++
Set ID of token
+++
|[[name]]`name`|`String`|
+++
Set name of token
+++
|[[rules]]`rules`|`String`|
+++
Set rules for token
+++
|[[type]]`type`|`link:enums.html#AclTokenType[AclTokenType]`|
+++
Set type of token
+++
|===

[[BlockingQueryOptions]]
== BlockingQueryOptions

++++
 Options used to perform blocking query that used to wait for a potential change using long polling.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[index]]`index`|`Number (long)`|
+++
Set index indicating that the client wishes to wait for any changes subsequent to that index.
+++
|[[wait]]`wait`|`String`|
+++
Specifying a maximum duration for the blocking request. This is limited to 10 minutes.
 If not set, the wait time defaults to 5 minutes. This value can be specified in the form of "10s" or "5m"
 (i.e., 10 seconds or 5 minutes, respectively).
+++
|===

[[Check]]
== Check

++++
 Holds check properties
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[id]]`id`|`String`|
+++
Set the ID of check
+++
|[[name]]`name`|`String`|
+++
Set the name of check
+++
|[[nodeName]]`nodeName`|`String`|
+++
Set the name of node
+++
|[[notes]]`notes`|`String`|
+++
Set the human-readable note of check
+++
|[[output]]`output`|`String`|
+++
Set the output of check
+++
|[[serviceId]]`serviceId`|`String`|
+++
Set the ID of service with which this check associated
+++
|[[serviceName]]`serviceName`|`String`|
+++
Set the name of service with which this check associated
+++
|[[status]]`status`|`link:enums.html#CheckStatus[CheckStatus]`|
+++
Set the status of check
+++
|===

[[CheckOptions]]
== CheckOptions

++++
 Options used to register checks in Consul.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[http]]`http`|`String`|
+++
Set HTTP address to check. Also you should set checking interval
+++
|[[id]]`id`|`String`|
+++
Set check ID
+++
|[[interval]]`interval`|`String`|
+++
Set checking interval
+++
|[[name]]`name`|`String`|
+++
Set check name. This is mandatory field
+++
|[[notes]]`notes`|`String`|
+++
Set check notes
+++
|[[script]]`script`|`String`|
+++
Set path to checking script. Also you should set checking interval
+++
|[[serviceId]]`serviceId`|`String`|
+++
Set the service ID to associate the registered check with an existing service provided by the agent.
+++
|[[status]]`status`|`link:enums.html#CheckStatus[CheckStatus]`|
+++
Set the check status to specify the initial state of the health check.
+++
|[[tcp]]`tcp`|`String`|
+++
Set TCP address to check. Also you should set checking interval
+++
|[[ttl]]`ttl`|`String`|
+++
Set Time to Live of check.
+++
|===

[[ConsulClientOptions]]
== ConsulClientOptions

++++
 Options used to create Consul client.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[aclToken]]`aclToken`|`String`|
+++
Set the ACL token. When provided, the client will use this token when making requests to the Consul
 by providing the "?token" query parameter. When not provided, the empty token, which maps to the 'anonymous'
 ACL policy, is used.
+++
|[[dc]]`dc`|`String`|
+++
Set the datacenter name. When provided, the client will use it when making requests to the Consul
 by providing the "?dc" query parameter. When not provided, the datacenter of the consul agent is queried.
+++
|[[host]]`host`|`String`|
+++
Set Consul host. Defaults to `localhost`
+++
|[[pemTrustOptions]]`pemTrustOptions`|`link:dataobjects.html#PemTrustOptions[PemTrustOptions]`|
+++
Set the trust options.
+++
|[[port]]`port`|`Number (int)`|
+++
Set Consul HTTP API port. Defaults to `8500`
+++
|[[ssl]]`ssl`|`Boolean`|
+++
Set whether SSL/TLS is enabled
+++
|[[timeoutMs]]`timeoutMs`|`Number (long)`|
+++
Sets the amount of time (in milliseconds) after which if the request does not return any data
 within the timeout period an failure will be passed to the handler and the request will be closed.
+++
|[[trustAll]]`trustAll`|`Boolean`|
+++
Set whether all server certificates should be trusted
+++
|===

[[Coordinate]]
== Coordinate

++++
 Holds network coordinates of node
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[adj]]`adj`|`Number (float)`|
+++
Set adjustment
+++
|[[err]]`err`|`Number (float)`|
+++
Set error
+++
|[[height]]`height`|`Number (float)`|
+++
Set height
+++
|[[node]]`node`|`String`|
+++
Set name of node
+++
|[[vec]]`vec`|`Array of Number (Float)`|
+++
Set vector
+++
|===

[[CoordinateList]]
== CoordinateList

++++
 Holds result of network coordinates query
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[index]]`index`|`Number (long)`|
+++
Set Consul index, a unique identifier representing the current state of the requested coordinates
+++
|[[list]]`list`|`Array of link:dataobjects.html#Coordinate[Coordinate]`|
+++
Set list of coordinates
+++
|===

[[DcCoordinates]]
== DcCoordinates

++++
 Holds coordinates of servers in datacenter
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[datacenter]]`datacenter`|`String`|
+++
Set datacenter
+++
|[[servers]]`servers`|`Array of link:dataobjects.html#Coordinate[Coordinate]`|
+++
Set list of servers in datacenter
+++
|===

[[Event]]
== Event

++++
 Holds properties of Consul event
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[id]]`id`|`String`|
+++
Set ID of event
+++
|[[lTime]]`lTime`|`Number (int)`|
+++
Set the Lamport clock time
+++
|[[name]]`name`|`String`|
+++
Set name of event
+++
|[[node]]`node`|`String`|
+++
Set regular expression to filter by node name
+++
|[[payload]]`payload`|`String`|
+++
Set payload of event
+++
|[[service]]`service`|`String`|
+++
Set regular expression to filter by service
+++
|[[tag]]`tag`|`String`|
+++
Set regular expression to filter by tag
+++
|[[version]]`version`|`Number (int)`|
+++
Set version
+++
|===

[[EventList]]
== EventList

++++
 Holds result of events query
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[index]]`index`|`Number (long)`|
+++
Set Consul index, a unique identifier representing the current state of the requested events
+++
|[[list]]`list`|`Array of link:dataobjects.html#Event[Event]`|
+++
Set list of events
+++
|===

[[EventOptions]]
== EventOptions

++++
 Options used to trigger a new user event.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[node]]`node`|`String`|
+++
Set regular expression to filter by node name
+++
|[[payload]]`payload`|`String`|
+++
Set payload of event
+++
|[[service]]`service`|`String`|
+++
Set regular expression to filter by service
+++
|[[tag]]`tag`|`String`|
+++
Set regular expression to filter by tag
+++
|===

[[KeyValue]]
== KeyValue

++++
 Represents key/value pair stored in Consul
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[createIndex]]`createIndex`|`Number (long)`|
+++
Set the internal index value that represents when the entry was created.
+++
|[[flags]]`flags`|`Number (long)`|
+++
Set the flags attached to this entry. Clients can choose to use this however makes sense for their application.
+++
|[[key]]`key`|`String`|
+++
Set the key
+++
|[[lockIndex]]`lockIndex`|`Number (long)`|
+++
Set the number of times this key has successfully been acquired in a lock.
+++
|[[modifyIndex]]`modifyIndex`|`Number (long)`|
+++
Set the last index that modified this key.
+++
|[[session]]`session`|`String`|
+++
Set the session that owns the lock
+++
|[[value]]`value`|`String`|
+++
Set the value
+++
|===

[[KeyValueList]]
== KeyValueList

++++
 Holds result of key/value pairs query
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[index]]`index`|`Number (long)`|
+++
Set Consul index
+++
|[[list]]`list`|`Array of link:dataobjects.html#KeyValue[KeyValue]`|
+++
Set list of key/value pairs
+++
|===

[[KeyValueOptions]]
== KeyValueOptions

++++
 Options used to put key/value pair to Consul.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[acquireSession]]`acquireSession`|`String`|
+++
Set session ID for lock acquisition operation.
+++
|[[casIndex]]`casIndex`|`Number (long)`|
+++
Set the Check-And-Set index. If the index is <code>0</code>, Consul will only put the key if it does not already exist.
 If the index is non-zero, the key is only set if the index matches the ModifyIndex of that key.
+++
|[[flags]]`flags`|`Number (long)`|
+++
Set the flags. Flags is an value between <code>0</code> and 2<sup>64</sup>-1 that can be attached to each entry.
 Clients can choose to use this however makes sense for their application.
+++
|[[releaseSession]]`releaseSession`|`String`|
+++
Set session ID for lock release operation.
+++
|===

[[MaintenanceOptions]]
== MaintenanceOptions

++++
 Options used to placing a given service into "maintenance mode".
 During maintenance mode, the service will be marked as unavailable
 and will not be present in DNS or API queries. Maintenance mode is persistent
 and will be automatically restored on agent restart.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[enable]]`enable`|`Boolean`|
+++
Set maintenance mode to enabled: <code>true</code> to enter maintenance mode or <code>false</code> to resume normal operation.
 This flag is required.
+++
|[[id]]`id`|`String`|
+++
Set the ID of service. This field is required.
+++
|[[reason]]`reason`|`String`|
+++
Set the reason message. If provided, its value should be a text string explaining the reason for placing
 the service into maintenance mode. This is simply to aid human operators.
+++
|===

[[Node]]
== Node

++++
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[address]]`address`|`String`|
+++
Set node address
+++
|[[lanAddress]]`lanAddress`|`String`|
+++
Set node lan address
+++
|[[name]]`name`|`String`|
+++
Set node name
+++
|[[wanAddress]]`wanAddress`|`String`|
+++
Set node wan address
+++
|===

[[NodeList]]
== NodeList

++++
 Holds result of nodes query
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[index]]`index`|`Number (long)`|
+++
Set Consul index, a unique identifier representing the current state of the requested list of nodes
+++
|[[list]]`list`|`Array of link:dataobjects.html#Node[Node]`|
+++
Set list of nodes
+++
|===

[[NodeQueryOptions]]
== NodeQueryOptions

++++
 Options used to requesting list of nodes
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[blockingOptions]]`blockingOptions`|`link:dataobjects.html#BlockingQueryOptions[BlockingQueryOptions]`|
+++
Set options for blocking query
+++
|[[near]]`near`|`String`|
+++
Set node name for sorting the list in ascending order based on the estimated round trip time from that node.
+++
|===

[[Service]]
== Service

++++
 Holds properties of service and node that its containing
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[address]]`address`|`String`|
+++
Set service address
+++
|[[id]]`id`|`String`|
+++
Set ID of service
+++
|[[name]]`name`|`String`|
+++
Set service name
+++
|[[node]]`node`|`String`|
+++
Set node name
+++
|[[nodeAddress]]`nodeAddress`|`String`|
+++
Set node address
+++
|[[port]]`port`|`Number (int)`|
+++
Set service port
+++
|[[tags]]`tags`|`Array of String`|
+++
Set list of service tags
+++
|===

[[ServiceEntry]]
== ServiceEntry

++++
 Holds properties of service, node and related checks
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[checks]]`checks`|`Array of link:dataobjects.html#Check[Check]`|
+++
Set list of checks
+++
|[[node]]`node`|`link:dataobjects.html#Node[Node]`|
+++
Set node
+++
|[[service]]`service`|`link:dataobjects.html#Service[Service]`|
+++
Set service
+++
|===

[[ServiceEntryList]]
== ServiceEntryList

++++
 Holds list of services, nodes and related checks
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[index]]`index`|`Number (long)`|
+++
Set Consul index, a unique identifier representing the current state of the requested list of services
+++
|[[list]]`list`|`Array of link:dataobjects.html#ServiceEntry[ServiceEntry]`|
+++
Set list of services
+++
|===

[[ServiceList]]
== ServiceList

++++
 Holds result of services query
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[index]]`index`|`Number (long)`|
+++
Set Consul index, a unique identifier representing the current state of the requested list of services
+++
|[[list]]`list`|`Array of link:dataobjects.html#Service[Service]`|
+++
Set list of services
+++
|===

[[ServiceOptions]]
== ServiceOptions

++++
 Options used to register service.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[address]]`address`|`String`|
+++
Set service address
+++
|[[checkOptions]]`checkOptions`|`link:dataobjects.html#CheckOptions[CheckOptions]`|
+++
Set check options of service
+++
|[[id]]`id`|`String`|
+++
Set the ID of session
+++
|[[name]]`name`|`String`|
+++
Set service name
+++
|[[port]]`port`|`Number (int)`|
+++
Set service port
+++
|[[tags]]`tags`|`Array of String`|
+++
Set list of tags associated with service
+++
|===

[[ServiceQueryOptions]]
== ServiceQueryOptions

++++
 Options used to requesting list of services
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[blockingOptions]]`blockingOptions`|`link:dataobjects.html#BlockingQueryOptions[BlockingQueryOptions]`|
+++
Set options for blocking query
+++
|[[near]]`near`|`String`|
+++
Set node name for sorting the list in ascending order based on the estimated round trip time from that node.
+++
|[[tag]]`tag`|`String`|
+++
Set tag for filtering request results
+++
|===

[[Session]]
== Session

++++
 Holds properties of Consul sessions
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[checks]]`checks`|`Array of String`|
+++
Set the list of associated health checks
+++
|[[createIndex]]`createIndex`|`Number (long)`|
+++
Set the create index of session
+++
|[[id]]`id`|`String`|
+++
Set the ID of node
+++
|[[index]]`index`|`Number (long)`|
+++
Set Consul index
+++
|[[lockDelay]]`lockDelay`|`Number (long)`|
+++
Set the Lock delay of session
+++
|[[node]]`node`|`String`|
+++
Set the ID of node
+++
|===

[[SessionList]]
== SessionList

++++
 Holds result of sessions query
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[index]]`index`|`Number (long)`|
+++
Set Consul index, a unique identifier representing the current state of the requested list of sessions
+++
|[[list]]`list`|`Array of link:dataobjects.html#Session[Session]`|
+++
Set list of sessions
+++
|===

[[SessionOptions]]
== SessionOptions

++++
 Options used to create session.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[behavior]]`behavior`|`link:enums.html#SessionBehavior[SessionBehavior]`|
+++
Set the behavior when a session is invalidated. The release behavior is the default if none is specified.
+++
|[[checks]]`checks`|`Array of String`|
+++
Set a list of associated health checks. It is highly recommended that,
 if you override this list, you include the default "serfHealth"
+++
|[[lockDelay]]`lockDelay`|`Number (long)`|
+++
Set the lock-delay period.
+++
|[[name]]`name`|`String`|
+++
Set the human-readable name for the Session
+++
|[[node]]`node`|`String`|
+++
Set the node to which the session will be assigned
+++
|[[ttl]]`ttl`|`Number (long)`|
+++
Set the TTL interval. When TTL interval expires without being renewed, the session has expired
 and an invalidation is triggered. If specified, it must be between 10s and 86400s currently.
+++
|===

[[TxnError]]
== TxnError

++++
 Holds information describing which operations failed if the transaction was rolled back.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[opIndex]]`opIndex`|`Number (int)`|
+++
Set the index of the failed operation in the transaction
+++
|[[what]]`what`|`String`|
+++
Set error message about why that operation failed.
+++
|===

[[TxnKVOperation]]
== TxnKVOperation

++++
 Holds operation to apply to the key/value store inside a transaction
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[flags]]`flags`|`Number (long)`|
+++
Set the flags attached to this entry. Clients can choose to use this however makes sense for their application.
+++
|[[index]]`index`|`Number (long)`|
+++
Set the index used for locking, unlocking, and check-and-set operations.
+++
|[[key]]`key`|`String`|
+++
Set the key
+++
|[[session]]`session`|`String`|
+++
Set the session used for locking, unlocking, and check-and-set operations.
+++
|[[type]]`type`|`link:enums.html#TxnKVVerb[TxnKVVerb]`|
+++
Set the type of operation to perform
+++
|[[value]]`value`|`String`|
+++
Set the value
+++
|===

[[TxnRequest]]
== TxnRequest

++++
 Holds list of operations in transaction
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[operationsSize]]`operationsSize`|`Number (int)`|
+++
Returns the number of operations in this request
+++
|===

[[TxnResponse]]
== TxnResponse

++++
 Holds results of transaction
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[errors]]`errors`|`Array of link:dataobjects.html#TxnError[TxnError]`|
+++
Adds error to this response
+++
|[[errorsSize]]`errorsSize`|`Number (int)`|
+++
Returns the number of errors in this response
+++
|[[resultsSize]]`resultsSize`|`Number (int)`|
+++
Returns the number of results in this response
+++
|===

